### ISSUE TITLE
[Feature Request] Store dashboard configuration in database

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#858] opened 2023-09-21 07:25 UTC
**Problem description**
In the researcher UI it is tedious and error prone to fill in the new task form every time for a similar or identical task. Therefore I would like to store a JSON(?) blop in the database which contains the configuration of this dashboard. One of the configuration options should be a reference to a *template task* see issue #857.

The dashboard should be coupled to a collaboration (or maybe to a study #812?)

**Comment by bartvanb** [comment] 2023-11-09 09:45
Duplicate of #857

**Closed by bartvanb** 2023-11-09 09:45 UTC
Labels: feature-request
