### ISSUE TITLE
[Bug] KeyError: 'server_url' when running vnode start --user --name [node-name]

### ISSUE THREAD

**Issue by yannick-vinkesteijn** [vantage6/vantage6#962] opened 2024-01-03 09:18 UTC
**Describe the bug**
After installing a node when using vnode start --user --name [node-name] A keyError appears for the server_url in the config yaml file. I checked the config file and server_url is present.

**To Reproduce**
1. setup a node with `vnode new --user --name [node-name]`
2. create a private key with `vnode create-private-key`
3. edit config to add private key path and re-enable encryption
4. start node with `vnode start --user --name [node-name]`

**Expected behavior**
I expected the node to start.

**Details**
 - OS: ubuntu 22.04 (azure VM)
 - vantage6 4.1.2
- Docker version 24.0.7, build afdd53b

**Error log**
```
Traceback (most recent call last):
  File "/home/vantage-node/vantage6-venv/bin/vnode", line 8, in <module>
    sys.exit(cli_node())
  File "/home/vantage-node/vantage6-venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/vantage-node/vantage6-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/vantage-node/vantage6-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vantage-node/vantage6-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vantage-node/vantage6-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/vantage-node/vantage6-venv/lib/python3.10/site-packages/vantage6/cli/node/start.py", line 126, in cli_node_start
    client = create_client(ctx)
  File "/home/vantage-node/vantage6-venv/lib/python3.10/site-packages/vantage6/cli/node/common/__init__.py", line 45, in create_client
    host = ctx.config['server_url']
KeyError: 'server_url'
```

**Comment by bartvanb** [comment] 2024-01-05 14:19
Hi @yannick-vinkesteijn, thanks for reporting this issue!
 
Unfortunately, I cannot reproduce the issue in a clean conda environment with v4.1.2. So can you check the following:
- In your final configuration file, do you see a `server_url` key?
- Can you repeat the first step, and check if, before manual editing, you see a `server_url` key?
- Can you start the config file before editing it manually?

**Comment by yannick-vinkesteijn** [comment] 2024-01-08 10:38
@bartvanb I made a new node and now I don't have this issue. Is it possible to properly update the config of an existing node.

**Comment by bartvanb** [comment] 2024-01-08 11:04
Alright that's good to hear! Since the issue appears to be resolved I am closing the issue, but feel free to open it again if it turns out otherwise.

**Closed by bartvanb** 2024-01-08 11:04 UTC
Labels: bug, New
