### ISSUE TITLE
[Feature Request] add `wait_for_results` to the `AlgorithmClient`

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#712] opened 2023-06-14 14:06 UTC
**Problem description**
No reason it isnt there. Should probably add it to `BaseClient`.

**Comment by bartvanb** [comment] 2023-06-20 15:32
Duplicate of #651

**Closed by bartvanb** 2023-06-20 15:32 UTC
Labels: feature-request, New

**Comment by frankcorneliusmartin** [comment] 2023-06-22 07:57
Can't we add this in version 3?
