### ISSUE TITLE
[Bug] vantage6 cli: fails to create new node config if ~/.config does not exist

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1095] opened 2024-03-14 14:14 UTC
**Describe the bug**

Minor issue. If ~/.config does not exist, it errors out after asking for name.

**To Reproduce**
1. Log as a user that doesn't have ~/.config
2. ```
    $ v6 node new
    ? Please enter a configuration-name: test
    [warn ] - Target directory '/home/user/.config' for configuration file does not exist.
    [error] - Cannot write configuration file. Exiting...
    ```

**Expected behavior**
Either creating the ~/.config, or erroring out as soon as you execute v6 node new, not after asking for configuration-name.

**Details**
- Vantage6 version: 4.3.0

**Comment by bartvanb** [comment] 2024-03-15 14:46
Very related/Duplicate of #938

**Closed** 2024-05-14 07:41 UTC
Labels: bug, New
